name: Simple Compilation

on:
  pull_request:
    branches: [ "main" ] # this is necessary to run the workflow on pull requests
  push:
    branches: [ "main" ] # this is necessary to run the workflow on pushes
  workflow_dispatch: # this is necessary if you want to run the workflow manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # this checks the repository for changes and updates the local copy

      - name: Set up Node.js
        uses: actions/setup-node@v4 # this sets up the Node.js environment necessary for the build
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies # this installs the dependencies necessary for the build
        run: npm ci

      - name: Run build # this runs the build process
        run: npm run build
    
